# Custom sign key
sign_salt: salt

debug: false

redis:
  host: localhost
  port: 6379
  db:   0

# The real ip header passed by reverse proxy (Apache, Nginx etc.)
# None:       null
# Apache:     X-Forwarded-For
# Nginx:      X-Real-IP
# CloudFlare: CF-Connecting-IP
ip_header: null

# Netease Cloud Music API Key
encrypt:  
  e: >-
    010001

  n: >-
    00e0b509f6259df8642dbc35662901477df22677ec152b5ff68ace615
    bb7b725152b3ab17a876aea8a5aa76d2e417629ec4ee341f56135fccf
    695280104e0312ecbda92557c93870114af6c9d05c4f7f0c3685b7a46
    bee255932575cce10b424d813cfe4875d3e82047b97ddef52741d546b
    8e289dc6935b3ece0462db0a22b8e7

  nonce: >-
    0CoJUm6Qyw8W8jud

# Google reCAPTCHA key
recaptcha: false
# 下面的東西在 recaptcha 為 false 的時候需要註解掉不然會出事
#  secret:  secret
#  sitekey: sitekey

ssl: false
